# Generated by Django 4.2.13 on 2024-06-24 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0004_note_userprofile_created_at_userprofile_trashed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="harmony.userprofile",
            ),
        ),
    ]
