# Generated by Django 4.2.13 on 2024-06-25 21:23

from django.db import migrations, models
import harmony.validators


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0005_note_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagenote",
            name="image",
            field=models.ImageField(
                upload_to="notes/images",
                validators=[harmony.validators.image_size_validator],
            ),
        ),
        migrations.AlterField(
            model_name="synch",
            name="picture",
            field=models.ImageField(
                upload_to="synchs/pictures",
                validators=[harmony.validators.image_size_validator],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                upload_to="users/pictures",
                validators=[harmony.validators.image_size_validator],
            ),
        ),
    ]
