# Generated by Django 4.2.13 on 2024-06-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(upload_to="users/pictures"),
        ),
    ]
