# Generated by Django 4.2.13 on 2024-06-29 07:35

from django.db import migrations, models
import harmony.validators


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0006_alter_imagenote_image_alter_synch_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/pictures",
                validators=[harmony.validators.image_size_validator],
            ),
        ),
    ]
