# Generated by Django 4.2.13 on 2024-07-01 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0007_alter_userprofile_picture"),
    ]

    operations = [
        migrations.RenameField(model_name="note", old_name="sender", new_name="taker",),
        migrations.CreateModel(
            name="SynchMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("trashed_at", models.DateTimeField(null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synchs",
                        to="harmony.synch",
                    ),
                ),
                (
                    "synch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="harmony.synch",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
