# Generated by Django 4.2.13 on 2024-07-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0008_rename_sender_note_taker_synchmembership"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stream", old_name="created_by", new_name="creator",
        ),
        migrations.RenameField(
            model_name="synch", old_name="created_by", new_name="creator",
        ),
    ]
