# Generated by Django 4.2.13 on 2024-07-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0009_rename_created_by_stream_creator_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="synchmembership", old_name="profile", new_name="member",
        ),
    ]
