# Generated by Django 4.2.13 on 2024-07-02 17:27

from django.db import migrations, models
import django.db.models.deletion
import harmony.validators


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0010_rename_profile_synchmembership_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synch",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="synchs/pictures",
                validators=[harmony.validators.image_size_validator],
            ),
        ),
        migrations.AlterField(
            model_name="synchmembership",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="synchs",
                to="harmony.userprofile",
            ),
        ),
    ]
