# Generated by Django 4.2.13 on 2024-07-04 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0012_rename_title_stream_name_rename_title_synch_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
