# Generated by Django 4.2.13 on 2024-07-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0014_alter_synchmembership_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="membership_type",
            field=models.CharField(
                choices=[("EV", "Everyone"), ("ME", "Me Only"), ("CU", "Custom")],
                default="EV",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="StreamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("resolved", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="harmony.userprofile",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="harmony.stream",
                    ),
                ),
            ],
            options={"unique_together": {("stream", "member")},},
        ),
    ]
