# Generated by Django 4.2.13 on 2024-07-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0015_stream_membership_type_streammembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="streammembership",
            name="new",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="streammembership",
            name="order",
            field=models.IntegerField(null=True),
        ),
    ]
