# Generated by Django 4.2.13 on 2024-07-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0016_streammembership_new_alter_streammembership_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="membership_type",
            field=models.CharField(
                choices=[("EVE", "Everyone"), ("MEO", "Me Only"), ("CUS", "Custom")],
                default="EVE",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="streammembership",
            name="new",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="streammembership",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
