# Generated by Django 4.2.13 on 2024-07-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0017_alter_stream_membership_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="streammembership", name="new",),
        migrations.RemoveField(model_name="streammembership", name="resolved",),
        migrations.AddField(
            model_name="streammembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("ACT", "Active"),
                    ("RES", "Resolved"),
                    ("DNC", "Does Not Concern Me"),
                ],
                default="NEW",
                max_length=3,
            ),
        ),
    ]
