# Generated by Django 4.2.13 on 2024-07-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harmony", "0018_remove_streammembership_new_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="streammembership",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="streammembership",
            name="trashed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="streammembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
